# Generated by Django 4.1.1 on 2022-09-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_create_on_contact_created_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="organisation",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone_number",
            field=models.CharField(max_length=14, null=True),
        ),
    ]
